import { SessionConfig } from './axis-prompt';

export type Language = 'en' | 'es';

interface ExportMetadata {
  sessionId: string;
  timestamp: string;
  config: SessionConfig;
  language: Language;
}

const translations = {
  en: {
    sessionBrief: 'Clinical Session Brief',
    sessionId: 'Session ID',
    timestamp: 'Date & Time',
    challengeLevel: 'Challenge Level',
    intention: 'Intention',
    activityType: 'Activity Type',
    helpType: 'Help Type',
    urgency: 'Urgency',
    entryState: 'Entry State',
    whatMoved: 'What Moved',
    openThreads: 'Open Threads',
    patterns: 'Patterns',
    workingHypotheses: 'Working Hypotheses',
    exitState: 'Exit State',
    generatedBy: 'Generated by AXIS Session Protocol',
    exportedOn: 'Exported on',
  },
  es: {
    sessionBrief: 'Resumen de Sesión Clínica',
    sessionId: 'ID de Sesión',
    timestamp: 'Fecha y Hora',
    challengeLevel: 'Nivel de Desafío',
    intention: 'Intención',
    activityType: 'Tipo de Actividad',
    helpType: 'Tipo de Ayuda',
    urgency: 'Urgencia',
    entryState: 'Estado de Entrada',
    whatMoved: 'Qué Se Movió',
    openThreads: 'Hilos Abiertos',
    patterns: 'Patrones',
    workingHypotheses: 'Hipótesis de Trabajo',
    exitState: 'Estado de Salida',
    generatedBy: 'Generado por Protocolo de Sesión AXIS',
    exportedOn: 'Exportado en',
  },
};

export function downloadSessionBrief(
  briefContent: string,
  config: SessionConfig,
  language: Language = 'en'
): void {
  const timestamp = new Date();
  const dateStr = timestamp.toISOString().split('T')[0];
  const timeStr = timestamp.toTimeString().split(' ')[0].replace(/:/g, '-');
  const filename = `AXIS-Session-Brief_${dateStr}_${timeStr}.md`;

  // Create markdown content with metadata
  const metadata = translations[language];
  const header = `# ${metadata.sessionBrief}

**${metadata.sessionId}:** ${generateSessionId()}
**${metadata.exportedOn}:** ${timestamp.toLocaleString(language === 'es' ? 'es-ES' : 'en-US')}

---

## ${metadata.sessionBrief} Metadata

| | |
|---|---|
| **${metadata.challengeLevel}** | ${config.challengeLevel} |
| **${metadata.intention}** | ${config.intention} |
| **${metadata.activityType}** | ${config.activityType} |
| **${metadata.helpType}** | ${config.helpType} |
| **${metadata.urgency}** | ${config.urgency} |

---

## ${metadata.sessionBrief}

${briefContent}

---

*${metadata.generatedBy}*
`;

  const blob = new Blob([header + briefContent], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function printSessionBrief(
  briefContent: string,
  config: SessionConfig,
  language: Language = 'en'
): void {
  const metadata = translations[language];
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const htmlContent = `
    <!DOCTYPE html>
    <html lang="${language}">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${metadata.sessionBrief}</title>
      <style>
        body {
          font-family: 'Georgia', serif;
          line-height: 1.6;
          color: #333;
          max-width: 800px;
          margin: 0 auto;
          padding: 40px 20px;
          background: white;
        }
        h1 {
          text-align: center;
          border-bottom: 2px solid #333;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        h2 {
          margin-top: 30px;
          margin-bottom: 15px;
          border-left: 4px solid #ddd;
          padding-left: 15px;
        }
        .metadata {
          background: #f5f5f5;
          padding: 15px;
          border-radius: 4px;
          margin-bottom: 30px;
        }
        .metadata-row {
          display: flex;
          margin: 8px 0;
        }
        .metadata-label {
          font-weight: bold;
          min-width: 150px;
        }
        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #ddd;
          font-size: 12px;
          color: #666;
          text-align: center;
        }
        @media print {
          body {
            padding: 0;
          }
        }
      </style>
    </head>
    <body>
      <h1>${metadata.sessionBrief}</h1>

      <div class="metadata">
        <div class="metadata-row">
          <span class="metadata-label">${metadata.sessionId}:</span>
          <span>${generateSessionId()}</span>
        </div>
        <div class="metadata-row">
          <span class="metadata-label">${metadata.exportedOn}:</span>
          <span>${new Date().toLocaleString(language === 'es' ? 'es-ES' : 'en-US')}</span>
        </div>
        <hr style="margin: 15px 0; border: none; border-top: 1px solid #ddd;">
        <div class="metadata-row">
          <span class="metadata-label">${metadata.challengeLevel}:</span>
          <span>${config.challengeLevel}</span>
        </div>
        <div class="metadata-row">
          <span class="metadata-label">${metadata.intention}:</span>
          <span>${config.intention}</span>
        </div>
        <div class="metadata-row">
          <span class="metadata-label">${metadata.activityType}:</span>
          <span>${config.activityType}</span>
        </div>
        <div class="metadata-row">
          <span class="metadata-label">${metadata.helpType}:</span>
          <span>${config.helpType}</span>
        </div>
        <div class="metadata-row">
          <span class="metadata-label">${metadata.urgency}:</span>
          <span>${config.urgency}</span>
        </div>
      </div>

      <div id="content">${briefContent}</div>

      <div class="footer">
        ${metadata.generatedBy}
      </div>
    </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();

  // Wait for content to load before printing
  setTimeout(() => {
    printWindow.print();
  }, 250);
}

function generateSessionId(): string {
  return `AXIS-${Date.now()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}`;
}

export function exportSessionToJSON(
  briefContent: string,
  config: SessionConfig,
  messages: Array<{ role: string; text: string }>,
  language: Language = 'en'
): void {
  const timestamp = new Date();
  const dateStr = timestamp.toISOString().split('T')[0];
  const timeStr = timestamp.toTimeString().split(' ')[0].replace(/:/g, '-');
  const filename = `AXIS-Session-Export_${dateStr}_${timeStr}.json`;

  const exportData = {
    metadata: {
      sessionId: generateSessionId(),
      timestamp: timestamp.toISOString(),
      language,
    },
    config,
    briefContent,
    messages,
  };

  const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
